# -*- coding: utf-8 -*-
"""Linear-Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W0Oqwujbo6w-sjCCZvrd5BKZbXah8smy
"""

import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

housing_data = pd.read_csv(r"/content/house_prices.csv")
housing_data.head()

# Machine Learning algorithms handles arrays and not Data-Frames
size = housing_data["sqft_living"]
price = housing_data["price"]

x = np.array(size).reshape(-1, 1)
y = np.array(price).reshape(-1, 1)

lr_model = LinearRegression()
lr_model.fit(x, y)

lr_model_error = mean_squared_error(x, y)
print("MSE : ", lr_model_error)
print("RMSE : ", math.sqrt(lr_model_error))
print("R squared value : ", lr_model.score(x, y))

# y= b0 + b1x
#b0 coeff
print(lr_model.intercept_[0])
#b1 coeff
print(lr_model.coef_[0])

# Visualize Data with Model
plt.scatter(x, y, color="green")
plt.plot(x, lr_model.predict(x), color="black")
plt.title("Linear Regression")
plt.xlabel("Size")
plt.ylabel("Price")
plt.show()

